server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/white_jotter?useSSL=false&&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


